### ISSUE TITLE
Use `>>>` as an alias for `opcompose`

### ISSUE THREAD

**Issue by josephmckinsey** [JuliaFunctional/CompositionsBase.jl#11]
In Haskell, the equivalent to ⨟ is [`>>>`](https://hackage.haskell.org/package/base-4.16.1.0/docs/Control-Arrow.html#v:-62--62--62-). This may go over better for those who are bound to ASCII.

Julia 1.7.2, at least, allows this. Probably it is because `>>` and `<<` are bit shift operators.

Please close if this is too much bikeshedding. It looks like you've already considered some other options in #3.

**Comment by jw3126** [comment]
Thanks @josephmckinsey, I think `>>>` is a nice symbol to represent (op)composition and I can totally imagine an alternate history, where we use it for composition. That being said I don't think we should support it here. My arguments are:
* Multiple aliases for the same thing add to complexity. Users need to keep the meaning of one more symbol in mind.
* `>>>` represents already the concept of bit shift in julia. A concept very different from composition. Functions should generally only represent a single concept.

**Comment by tkf** [comment]
I agree with everything @jw3126 mentioned.

It's also quite easy to play in the alternative universe where `>>>` is the `opcompose` :)

```julia
julia> using CompositionsBase: opcompose as >>>

julia> false |> (!) >>> >(0)
true
```

**Comment by josephmckinsey** [comment]
Alright. I'll consider this closed.
